### PR TITLE
Type definition

### PR DESCRIPTION
**Pull request by Akxe**
Please review if there is some other type for file input. Thanks

### CODE REVIEW

**Comment by JuanIrache** [comment]
I'm not qualified to review the TS parts. I can accept it if it doesn't interfere with other things

**Comment by Akxe** [comment]
I forgot to add return type. Will do and then we can merge tomorrow.

FYI: It does not affect the JS part of the library in any way at all.

**Comment by Akxe** [comment]
@JuanIrache What function can you pass to the `GPMFExtract` function as the `file` parameter?

**Comment by Akxe** [comment]
To sum it up; You can use the library the same way you used to, but now you have type information fully compatible with what the library can accept. 

Also, I added the possibility to import the function as named import. Not that it is needed, but it is a nice to have in TS.

It is ready to be merged :)

**Comment by JuanIrache** [comment]
Thank you. Merged. Could you make future changes in the dev branch instead of master?

**Comment by Akxe** [comment]
Will do. Browser compatibility branch is in progress ;)

**Pull request merged**
