### PR TITLE
Lighten package size

### PR DESCRIPTION
**Pull request by HugoPoi**
* Bump `mp4box` to address security issues, and [some weird dependencies of `npm`](https://github.com/gpac/mp4box.js/issues/223)
* Add `.npmignore` to avoid including tests files and especially samples in the package (You can check with `npm publish --dry-run`)

### CODE REVIEW

**Comment by JuanIrache** [comment]
Thanks @HugoPoi . Have you tested this on both the browser and NodeJS? Recent changes were breaking one or the other. Especially due to mp4box quirkiness... Also, could you send the PR to the dev branch so the automated tests run?

**Comment by HugoPoi** [comment]
`npm run test` finish ok, but I havn't tested in a browser yet.

**Comment by JuanIrache** [comment]
Thank you. I will test this when I get a moment. But if you gather more information, it is very much welcome.

The issues I'm concerned about are:
- This problem coming back: https://github.com/JuanIrache/gpmf-extract/issues/41 Which was addressed with this https://github.com/JuanIrache/gpmf-extract/commit/2f7b8bf82fe69824e8fa7c596c74059b7f3c9202
- Firefox crashing, which for some reason is prevented with this loop: https://github.com/JuanIrache/gpmf-extract/commit/2aa1df6463f4d6f3aa01481921bafba4b2893668
- And the update percentage not being reported correctly, Which was fixed with this: https://github.com/JuanIrache/gpmf-extract/commit/b6cccb4baabbb583c78126478ddf406770d02947

**Comment by JuanIrache** [comment]
Thanks again @HugoPoi , and sorry for the delay in merging this

**Pull request merged**
